### PR TITLE
Added mode: BigClock

### PR DESCRIPTION
**Pull request by rpalaguachi**
* Added new symbols to `signs.cpp` with bigger, bolder numerals.
* Added a new mode `BigClock` that displays the bolder numerals. This does **not** replace the existing clock mode.
* Replaced hardcoded integer values with enum constants.
* Rebuilt the web gui to run on ESP32

### CODE REVIEW

**Comment by rpalaguachi** [comment]
Sorry for the messy commit history 😅 . I'm trying to squash my commits and I keep messing it up somehow. I'll try to open a fresh PR tomorrow

**Comment by ph1p** [comment]
> Sorry for the messy commit history 😅 . I'm trying to squash my commits and I keep messing it up somehow. I'll try to open a fresh PR tomorrow

Thanks for the PR :) Don't stress and take the time you need.

**Comment by ph1p** [comment]
I noticed that the numbers look a little inconsistent. Maybe this will help you:
Screenshot 2023-01-12 at 12 45 46

**Comment by rpalaguachi** [comment]
How did you generate these so quickly!? I've been manually coding in binary
😆

**Comment by ph1p** [comment]
This is a little bit my fault, because I didn't describe it exactly 😅. If you go to Web GUI and click "Creator", you can create screens and download them via the download button as a generated .cpp.

**Comment by rpalaguachi** [comment]
Awesome, thanks! Don't worry, I enjoyed the exercise :p

Maybe add something to the README?

**Comment by ph1p** [comment]
> Awesome, thanks! Don't worry, I enjoyed the exercise :p

I'm glad to hear that :)

> Maybe add something to the README?

Defintively! I'm currently doing a rewrite/transition to another frontend library #11 and will consider it there.

**Pull request closed without merging**
