### PR TITLE
Support for 8266 nodemcuv2

### PR DESCRIPTION
**Pull request by jekkos**
Rebased against main branch and reopened the PR.

### CODE REVIEW

**Comment by cixio** [comment]
Getting some errors in Visual Studio Code on mac:

`include/mode/clock.h:19:6: error: default argument given for parameter 2 of 'bool getLocalTime(tm*, uint32_t)' [-fpermissive]`
fix: remove ` = 5000`

`src/mode/weather.cpp:44:15: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)`
fix: 
```
#include <WiFiClient.h>
WiFiClient wifiClient;
...
http.begin(wifiClient,weatherApiString);
```
(see: https://stackoverflow.com/questions/67702822/error-call-to-httpclientbegin-declared-with-attribute-error-obsolete-api )

More Bugs:
```
src/screen.cpp:146:10: error: reference to 'byte' is ambiguous
src/screen.cpp:147:10: error: 'bits' was not declared in this scope; did you mean 'bit'?
src/screen.cpp:149:10: error: reference to 'byte' is ambiguous
src/screen.cpp:153:46: error: 'counter' was not declared in this scope
src/screen.cpp:156:3: error: 'counter' was not declared in this scope
```
fix (line 146 + 149)
```
  static ::byte bits[ROWS * COLS / 8] = {0};
  static ::byte counter = 0;
```

After that I get a multiple definiton of getLocalTime - so removing that function from /src/mode/clock.cpp

Okay, now upload works - but after connection to LED Display nothing lights up and ESP 8622 does not connect to network...

...and here I can't get any further because I'm just a little playchild who can google well ;)

**Comment by jekkos** [comment]
I pushed a new commit, indeed the code also crashed for me, it seemed to be related to the timer. I removed this and am using SPI pins now instead to push the data from the regular main loop(). I do see some artifacts now and then in some animations. The clock animation is working fine so far however.

**Comment by jekkos** [comment]
Regading `getLocalTime` you are right, it should be in esp8266/time.cpp. I cannot see it in my package however.

**Comment by cixio** [comment]
okay, it works better now (clock, big clock, circle, draw, stars) but there are still some bugs:
- speed: seems to be some kind faster as my ttgo
- weather: crashes sometimes
- snake: point sometimes not visible
- breakout: top lines dissapear before ball reaches
- rain: just the first point is visible
- game of life: cant explain - start looks kind a crazy

i think this has something to do with the darker dots...

**Comment by jekkos** [comment]
Maybe the refresh rate is not high enough to make it work for pIdema with lower brightness. I need to work a bit further to see if I can run the SPI from an interrupt as well. At fitst everything was Ran through main loop but there was no per pixel brightness setting either.
You could try to fix the brightness to highest value to see if that works.

**Comment by jekkos** [comment]
@cixio I have now a basic per pixel brightness working using the timer1 interrupt on esp8266

* Enabling the timer only worked at first for a longer interval, so using a 256 prescaler and 320microsecond interval. This seemed not enought to have the brightness working correctly. 
* It seems that using the interrupt crashed when it is called while something is being read from flash, so the storage option needs to be disabled
* Also the analogWrite seems to use the timer1 as well, so once the brightness is set globally when the interface boots, then after the refresh cycle seemed to freeze
* After disabling these two I was able to lower the interrupt cycle to 30microseconds. The brightness looks better now.

So to enable this feature you have to disable two others. Also sometimes I still get a random crash, especially when running some of the heavier animations. There might still be something interfering with the interrupt handler. I read that all methods need to finish quickly enough (300ms) and that ideally all code that is ran on the interrupt is inline using IRAM_ATTR macro, which is not the case for SPI write..

**Comment by jekkos** [comment]
@ph1p I have tested this branch on esp32 now and it works fine as well, so ready to be merged?

**Review by ph1p — APPROVED** [review]

**Pull request merged**
