### PR TITLE
feat: add screen test code on init

### LINKED ISSUE #48: Any idea how to check if leds are working?
I successfully wired all connections to the Obegraensad and was working fine for 2 days. I had set clock to display.
And today I saw that LED hung on minutes (hours were already gone, not lit). So I restarted ESP32 and software is running fine under my ip address but no leds are lit.

I tried to re-program esp32 but still no luck with LEDs. I suspect something burned inside, like those chip controllers on each led board. Anyone has an idea what's going on?

The gif shows that after connecting usb cable, some leds flash for split of a second and they are gone. It happens even when esp32 is completely disconnected from the panel.

EDIT: new link
https://gifyu.com/image/SRsyt

### PR DESCRIPTION
**Pull request by schw4rzlicht**
Adds a pixel test pattern when starting up.

Closes #48.

### CODE REVIEW

**Comment by schw4rzlicht** [comment]
@ph1p do you have any feedback on changes or if you plan to merge the feature at all?

**Review by kohlsalem — APPROVED** [review]
Looks simple, straight forward and usefull to me

**Comment by OldDroid** [comment]
Works like a charm, thanks for the PR :)

**Comment by schw4rzlicht** [comment]
Rebased onto master. If there is no intention to merge this, I will close it soon tho.

**Pull request closed without merging**
